services:
  backend_michail:
    image: zagaryds/backend_michail:latest
    container_name: backend_michail
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: main_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - /etc/ssl/private/selfsigned.key:/etc/ssl/private/selfsigned.key:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend_michail
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
