version: '3.8'

services:
  schedule-app:
    build: .
    image: schedule-app
    container_name: schedule-app
    ports:
      - "8080:8080"
    volumes:
      - db-data:/app/database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/database/schedule.db
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: main_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - /etc/ssl/private/selfsigned.key:/etc/ssl/private/selfsigned.key:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - schedule-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local


