version: '3.8'

services:
  schedule-app:
    build: .
    image: schedule-app
    container_name: schedule-app
    ports:
      - "8080:8080"
    volumes:
      - db-data:/app/database
      - uploads:/uploads  # Добавляем монтирование директории для загрузки изображений
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/database/schedule.db   
volumes:
  db-data:
    driver: local
  uploads:  # Определяем новый том для изображений
    driver: local


